.MODEL SMALL
.STACK 100H
.DATA 
STRING DB 'HELLO WORLD','$'

.CODE
MAIN PROC 
    ; INITIALIZATION CODE 
    MOV AX, @DATA
    MOV DS, AX  
    
    ;LOAD THE STRING TO THE REGISTER
    ;FOR OUTPUT WE NEED TO LOAD THE DATA TO THE DX REGISTER 
    ;FOR PRINTING A STRING WE NEED MOV AH 09H
    LEA DX, STRING 
    MOV AH, 09H
    INT 21H
    
    
    ; TERMINATING THE PROGRAM
    MOV AH, 4CH
    INT 21H
    
MAIN ENDP
END MAIN
    
    
    